### ISSUE TITLE
bootstrap.sh fails on arch

### ISSUE THREAD

**Issue by dsheeler** [moddevices/mod-plugin-builder#1]
Getting these errors:

[INFO ]  =================================================================
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    cfns.gperf:101:1: error: 'const char\* libc_name_p(const char_, unsigned int)' redeclared inline with 'gnu_inline' attribute
[ERROR]    make[3]: *_\* [Makefile:1058: cp/except.o] Error 1
[ERROR]    make[2]: **\* [Makefile:3975: all-gcc] Error 2
[ERROR]    make[1]: **\* [Makefile:863: all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/100-gcc.sh@944]
[ERROR]  >>        called from: do_gcc_for_host[scripts/build/cc/100-gcc.sh@663]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc.sh@56]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/B - Known issues.txt'
[ERROR]
[ERROR](elapsed: 14:07.29)
[14:07] / make: **\* [ct-ng:152: build] Error 2

Seems to be related to this: https://github.com/jcmvbkbc/crosstool-NG/issues/24

**Comment by brummer10** [comment]
This happen as well on debian sid with gcc version 6.2.0 20161010
But the patch in link you give above fix it. 
The next fail comes then on glib
gdate.c:2497:7: error: format not a string literal, format string not checked [-Werror=format-nonliteral]

which could be fixed with this patch:
https://dev.openwrt.org/browser/trunk/tools/pkg-config/patches/001-glib-gdate-suppress-string-format-literal-warning.patch?rev=49342

after that the build works.

**Comment by falkTX** [comment]
I tried quite a few things to get this working, but everything failed.

For now I recommend to use gcc-4 or gcc-5 to build.
Like this:
```
export CC=gcc-4.8
export CXX=g++-4.8
./bootstrap.sh
```

**Comment by milksob** [comment]
Please, have a look at line 22:
`if [ ! -f patches/gcc/4.9.3/132-build_gcc-5_with_gcc-6.patch ]; then`

it tested 13**2**-build_gcc-5_with_gcc-6.patch file,
but all further operation is against #13**0**,

`wget https://raw.githubusercontent.com/crosstool-ng/crosstool-ng/5a5fcbe148acf35372ecac145816c3515e6b8839/patches/gcc/5.3.0/130-build_gcc-5_with_gcc-6.patch
    cp 130-build_gcc-5_with_gcc-6.patch patches/gcc/4.9.3/
    cp 130-build_gcc-5_with_gcc-6.patch patches/gcc/5.2.0/
    rm 130-build_gcc-5_with_gcc-6.patch`

**Comment by milksob** [comment]
Also CT_PATCH_NONE option in
${SOURCE_DIR}/toolchain/modduo.config
is highly suspicious.

**Comment by milksob** [comment]
CT_PATCH_BUNDLED_LOCAL and others have no effect, only
CT_PATCH_ORDER="bundled" does

**Comment by falkTX** [comment]
This has been fixed for a while, and there are now CI checks in place to ensure clean builds are good.
Closing
