### ISSUE TITLE
Out of date git URL in sord.mk

### ISSUE THREAD

**Issue by benheartland** [moddevices/mod-plugin-builder#121]
https://github.com/moddevices/mod-plugin-builder/blob/42adb50f009e0f42afd1a65da41d9354dcd01282/plugins-dep/package/sord/sord.mk#L8

Using
`SORD_SITE = http://git.drobilla.net/sord.git`
results in a 404 Not Found error from http://sources.buildroot.net

Changing the line to 
`SORD_SITE = https://github.com/drobilla/sord.git`
allows sord.mk to complete

**Comment by rominator1983** [comment]
works on my machine during bootstrap. @falkTX I think this can be closed.
