### ISSUE TITLE
Out of date git URL in sratom.mk

### ISSUE THREAD

**Issue by benheartland** [moddevices/mod-plugin-builder#122]
https://github.com/moddevices/mod-plugin-builder/blob/42adb50f009e0f42afd1a65da41d9354dcd01282/plugins-dep/package/sratom/sratom.mk#L8

`SRATOM_SITE = http://git.drobilla.net/sratom.git`
results in a 404 Not Found from http://sources.buildroot.net

Changing to 
`SRATOM_SITE = https://github.com/lv2/sratom.git`
allows sratom.mk to complete

**Comment by rominator1983** [comment]
works on my machine during bootstrap. @falkTX I think this can be closed.
