### ISSUE TITLE
build errors for x86_64 because of m4/SIGSTKSZ

### ISSUE THREAD

**Issue by henning** [moddevices/mod-plugin-builder#129]
I am trying to run bootstrap.sh for x86_64, but i run into a compile error (non-erroneous output omitted, let me know if I shall add the full output):

```
$ ./bootstrap.sh x86_64 all
...
In file included from /usr/include/signal.h:328,
                 from ./signal.h:52,
                 from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~
/usr/bin/gcc  -I.   -I/home/henning/mod-workdir/x86_64/host/usr/include  -O2 -I/home/henning/mod-workdir/x86_64/host/usr/include -c -o exitfail.o exitfail.c
/usr/bin/gcc  -I.   -I/home/henning/mod-workdir/x86_64/host/usr/include  -O2 -I/home/henning/mod-workdir/x86_64/host/usr/include -c -o fatal-signal.o fatal-signal.c
/usr/bin/gcc  -I.   -I/home/henning/mod-workdir/x86_64/host/usr/include  -O2 -I/home/henning/mod-workdir/x86_64/host/usr/include -c -o fd-hook.o fd-hook.c
make[5]: *** [Makefile:1842: c-stack.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [Makefile:1602: all] Error 2
make[3]: *** [Makefile:1506: all-recursive] Error 1
make[2]: *** [Makefile:1461: all] Error 2
make[1]: *** [package/pkg-generic.mk:198: /home/henning/mod-workdir/x86_64/build/host-m4-1.4.17/.stamp_built] Error 2
make: *** [Makefile:36: _all] Error 2
```

Some research shows that this seems to be a known issue somewhere in the m4 codebase, and there are also some possible patches, but seemingly only for newer versions of m4: https://git.buildroot.org/buildroot/tree/package/m4/0003-c-stack-stop-using-SIGSTKSZ.patch?id=5a9504831f3fa1ef3be334036c93da30150fde55
But I'm not sure if buildroot is the right location - there seem to be multiple versions and sources of m4 around in the toolchain.

Being not very experienced with this kind of embedded toolchains and the ways how they add patches to the libraries used, I tried a few things but am somehow stuck on how to resolve this properly. I simply don't understand where exactly to place the possible patches to work properly. I tried using newer versions of buildroot instead, but that also doesn't seem to be possible/simple.

Any hint on what to do about this?

**Comment by falkTX** [comment]
This would likely need a patch inside https://github.com/moddevices/mod-plugin-builder/tree/master/patches/packages/m4

My current workflow for such things is just to create a git repo inside the build folder where it fails, add the files to git for tracking changes, and then generate a patch from that.
So you will need `/home/henning/mod-workdir/x86_64/build/host-m4-1.4.17/` dir here.

**Comment by henning** [comment]
Thanks for the hint @falkTX - I tried this, but It's strange: 

When I do as you suggest and apply the patches(or more precise, this one https://git.buildroot.org/buildroot/plain/package/m4/0003-c-stack-stop-using-SIGSTKSZ.patch?id=5a9504831f3fa1ef3be334036c93da30150fde55 - and another one that I tried but that's the same beside some comments and newlines) I found, then run ./configure and make directly in this directory, I dont get the original error, but another one:

```
...
gcc    -I../lib -I../lib  -W -Wabi -Waddress -Waggressive-loop-optimizations -Wall -Warray-bounds -Wattributes -Wbad-function-cast -Wbuiltin-macro-redefined -Wcast-align -Wchar-subscripts -Wclobbered -Wcomment -Wcomments -Wcoverage-mismatch -Wcpp -Wdeprecated -Wdeprecated-declarations -Wdisabled-optimization -Wdiv-by-zero -Wdouble-promotion -Wempty-body -Wendif-labels -Wextra -Wformat-contains-nul -Wformat-extra-args -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wformat-zero-length -Wfree-nonheap-object -Wignored-qualifiers -Wimplicit -Wimplicit-function-declaration -Wimplicit-int -Winit-self -Winline -Wint-to-pointer-cast -Winvalid-memory-model -Winvalid-pch -Wjump-misses-init -Wlogical-op -Wmain -Wmaybe-uninitialized -Wmissing-braces -Wmissing-declarations -Wmissing-field-initializers -Wmissing-include-dirs -Wmissing-parameter-type -Wmissing-prototypes -Wmudflap -Wmultichar -Wnarrowing -Wnested-externs -Wnonnull -Wnormalized=nfc -Wold-style-declaration -Wold-style-definition -Woverflow -Woverlength-strings -Woverride-init -Wpacked -Wpacked-bitfield-compat -Wparentheses -Wpointer-arith -Wpointer-sign -Wpointer-to-int-cast -Wpragmas -Wreturn-local-addr -Wreturn-type -Wsequence-point -Wshadow -Wsizeof-pointer-memaccess -Wstack-protector -Wstrict-aliasing -Wstrict-overflow -Wstrict-prototypes -Wsuggest-attribute=const -Wsuggest-attribute=format -Wsuggest-attribute=noreturn -Wsuggest-attribute=pure -Wswitch -Wswitch-default -Wsync-nand -Wtrampolines -Wtrigraphs -Wtype-limits -Wuninitialized -Wunknown-pragmas -Wunsafe-loop-optimizations -Wunused -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-function -Wunused-label -Wunused-local-typedefs -Wunused-macros -Wunused-parameter -Wunused-result -Wunused-value -Wunused-variable -Wvarargs -Wvariadic-macros -Wvector-operation-performance -Wvla -Wvolatile-register-var -Wwrite-strings -fdiagnostics-show-option -funit-at-a-time -Werror -g -O2 -MT m4.o -MD -MP -MF $depbase.Tpo -c -o m4.o m4.c &&\
mv -f $depbase.Tpo $depbase.Po
gcc: warning: switch '-Wmudflap' is no longer supported
cc1: error: '-Wabi' won't warn about anything [-Werror=abi]
cc1: note: '-Wabi' warns about differences from the most up-to-date ABI, which is also used by default
cc1: note: use e.g. '-Wabi=11' to warn about changes from GCC 7
m4.c:145:1: error: 'pure' attribute on function returning 'void' [-Werror=attributes]
  145 | {
      | ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:1512: m4.o] Error 1
make[2]: Leaving directory '/home/henning/data/produktion/sound-software-dev/mod/mod-plugin-builder/x86_64/build/host-m4-1.4.17/src'
make[1]: *** [Makefile:1506: all-recursive] Error 1
make[1]: Leaving directory '/home/henning/data/produktion/sound-software-dev/mod/mod-plugin-builder/x86_64/build/host-m4-1.4.17'
make: *** [Makefile:1461: all] Error 2
```

BUT when I run `make distclean` to remove any old stuff, and go back to running ``./bootstrap.sh x86_64``` in the main directory, I get the same error as previously. And the host-m4-1.4.17 directory where I applied the patch didn't even get a configure run apparently, so I wonder if it's even used.

What was the last time / commit ID this has been seen to work? 
Or is it rather something on my system that isn't right / can be set differently? Should I better try on a Debian system?

**Comment by falkTX** [comment]
After you place the patch file in the dir I told you, just delete the host-m4 folder completely and re-run bootstrap.
Dont run any other things manually, everything needs to go through bootstrap (which runs buildroot)

**Comment by henning** [comment]
Wait, that's not correct... I realize I was in the wrong directory! 

The directory x86_64/build/host-m4-1.4.17/ exists in both - the mod-workdir as well as the original plugin builder git clone dir, and I modified the m4 code only in the latter. Obviously I do not yet understand this build system well enough and am just hacking around amateurishly..

It's still true that I get the error as described when running make directly there in the host-m4-1.4.17 directory, but I am now rebuilding the stuff in mod-workdir and going to try the patching there and see what it does. I assume it might be different when running the build in the full toolchain instead of my system's gcc, libs, etc.

**Comment by henning** [comment]
OK, when doing the change in the right directory, there is no build error for m4 anymore, and it runs for quite some while.
I am going to put that patch in the correct place and send a Pull Request for it's addition.

Bootstrap now ends with a make error, but there is also a "ignored" - I am not sure if that is fully correct now:

```
make[1]: [Makefile:616: target-finalize] Error 1 (ignored)
find /home/henning/mod-workdir/x86_64/target -type f \( -perm /111 -o -name '*.so*' \) -not \( -name 'libpthread*.so*' -o -name 'ld-*.so*' -o -name '*.ko' \) -print0 | xargs -0 /home/henning/mod-workdir/x86_64/host/usr/bin/x86_64-mod-linux-gnu-strip --remove-section=.comment --remove-section=.note 2>/dev/null || true
if test -d /home/henning/mod-workdir/x86_64/target/lib/modules; then \
	find /home/henning/mod-workdir/x86_64/target/lib/modules -type f -name '*.ko' -print0 | \
	xargs -0 -r /home/henning/mod-workdir/x86_64/host/usr/bin/x86_64-mod-linux-gnu-strip --remove-section=.comment --remove-section=.note --strip-unneeded; fi
find /home/henning/mod-workdir/x86_64/target/lib -type f -name 'libpthread*.so*' | \
	xargs -r /home/henning/mod-workdir/x86_64/host/usr/bin/x86_64-mod-linux-gnu-strip --remove-section=.comment --remove-section=.note --strip-debug
find /home/henning/mod-workdir/x86_64/target/lib -type f -name 'ld-*.so*' | \
	xargs -r /home/henning/mod-workdir/x86_64/host/usr/bin/x86_64-mod-linux-gnu-strip --remove-section=.comment --remove-section=.note --strip-debug
test -f /home/henning/mod-workdir/x86_64/target/etc/ld.so.conf && \
	{ echo "ERROR: we shouldn't have a /etc/ld.so.conf file"; exit 1; } || true
test -d /home/henning/mod-workdir/x86_64/target/etc/ld.so.conf.d && \
	{ echo "ERROR: we shouldn't have a /etc/ld.so.conf.d directory"; exit 1; } || true
mkdir -p /home/henning/mod-workdir/x86_64/target/etc
( \
	echo "NAME=Buildroot"; \
	echo "VERSION=2016.02"; \
	echo "ID=buildroot"; \
	echo "VERSION_ID=2016.02"; \
	echo "PRETTY_NAME=\"Buildroot 2016.02\"" \
) >  /home/henning/mod-workdir/x86_64/target/etc/os-release

```

But it seems like I can run the build commands and the validation, too.

**Comment by henning** [comment]
Verified the build as discussed with a clean mod-workdir and everything removed in the local git clone, works so far and I created the pull request.

Only thing I'm not sure about is author crediting/license stuff - I hope it is correct/enough to mention the source URL and have all the original authors commit message and Email in.

**Comment by falkTX** [comment]
Closing as the build completes now without issues.
