### ISSUE TITLE
some issues on debian/sid

### ISSUE THREAD

**Issue by brummer10** [moddevices/mod-plugin-builder#32]
Hi
I run into some issues when building on a new setup debian/sid machine. 
I tried with gcc-8 and gcc-5 without success, then finally use  gcc-6.  
First stop was at:

> zconf.hash.c:167:1: error: conflicting types for ‘kconf_id_lookup’
> kconf_id_lookup (register const char *str, register size_t len)
> ^~~~~~~~~~~~~~~
> zconf.hash.c:34:31: note: previous declaration of ‘kconf_id_lookup’ was here
> static const struct kconf_id *kconf_id_lookup(register const char *str, register unsigned int len);
> ^~~~~~~~~~~~~~~

which could be solved by edit mod-workdir/build/crosstool-ng-1.22.0/kconfig/zconf.hash.c line 34 and change unsined int to size_t. delete the .stamp_configured in crosstool-ng-1.22.0 and re-run ./bootstrap.sh

next stop was at:

> Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/

which could be solved by replace the line 3936 in mod-workdir/plugins-dep/host/usr/bin/automake with:
`$text =~ s/\$\{([^ \t=:+\{\}]+)\}/substitute_ac_subst_variables_worker ($1)/ge;`

next stop was at:

> ./python -E -S -m sysconfig --generate-posix-vars ;\
> if test $? -ne 0 ; then \
>  echo "generate-posix-vars failed" ; \
>  rm -f ./pybuilddir.txt ; \
>  exit 1 ; \
> fi
>  Segmentation fault 
> generate-posix-vars failed

that could be solved by edit mod-workdir/plugins-dep/build/host-python-2.7.11/Include/objimpl.h applying this patch: https://github.com/python/cpython/commit/0b91f8a668201fc58fa732b8acc496caedfdbae0

after that, compilation finished successfully.
I put it here as reference for others who may try to build the mod-plugin-builder to save some time while search for solutions.

**Comment by brummer10** [comment]
Above I forgot to mention that I need to disable the build for camomile in mod-plugin-builder/plugins-dep/config.in and mod-plugin-builder/plugins-dep/modduo_defconfig

and it turns out that with this fixes it build as well with gcc-8 on debian/sid.

**Comment by cyrusadkisson** [comment]
Just like brummer10, I got stuck at the zconf error. His suggestion to change line 34 "unsigned int" to "size_t" got me past that first error.

Now I'm stuck at 

>>> toolchain-external undefined Configuring
Cannot execute cross-compiler '/home/cyrus/mod-workdir/toolchain/bin/arm-mod-linux-gnueabihf-gcc'
package/pkg-generic.mk:185: recipe for target '/home/cyrus/mod-workdir/plugins-dep/build/toolchain-external-undefined/.stamp_configured' failed
make: *** [/home/cyrus/mod-workdir/plugins-dep/build/toolchain-external-undefined/.stamp_configured] Error 1

I've tried apt installing some packages via "sudo apt-get install gcc-arm*" etc, but no help. Any ideas?

**Comment by cyrusadkisson** [comment]
Thanks. I missed those.

What's the prognosis on being able to compile on 18.04?

**Comment by brummer10** [comment]
removing camomile from the build instructions should do the trick.

**Comment by cyrusadkisson** [comment]
On 18.04? No. It's totally broken. The build seems to require gcc 4.9 and 18.04 only provides... get this either 4.8 or above 5... lol.

**Comment by brummer10** [comment]
Not that I'm thinking it's a good idea from the MOD team to ignore all the reports here, but, I've build the mod-plugin-builder with several different compilers, under others, I've used gcc 5 as well. 
In no case, I was able to build it without issues, fixing several things is required in any case.

**Comment by SteveALee** [comment]
@cyrusadkisson  I built on Ubuntu 18.04.1 LTS as described in #39.

Now I just need the Duo X to be delivered :)

**Comment by SteveALee** [comment]
Can I suggest that the note about libtool-bin is moved up to the section on dependencies? It is read where it is placed until much later.
