### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by romi1502** [moddevices/mod-plugin-builder#33]
When I try to build a docker image from the provided Dockerfile, using `docker build -t mod-plugin-builder docker`, I get the following error during the execution of the `./bootstrap.sh` script:

`package/pkg-generic.mk:185: recipe for target '/home/builder/mod-workdir/plugins-dep/build/camomile-713be25fe02676dda825e33ef4566b1c458daf4f/.stamp_configured' failed
make: *** [/home/builder/mod-workdir/plugins-dep/build/camomile-713be25fe02676dda825e33ef4566b1c458daf4f/.stamp_configured] Error 127
The command '/bin/sh -c ./bootstrap.sh && ./.clean-install.sh' returned a non-zero code: 2`

This is quite frustrating since this step of the build takes more than two hours on my computer.
I also tried to build the docker without the `./bootstrap.sh && ./.clean-install.sh` and ran the `bootstrap.sh` from within the docker container but got the same error.

I'm running Docker 18.06.1-ce, on Mac OS 10.13.6.

**Comment by brummer10** [comment]
see here how I solve it for the linux build:
https://github.com/moddevices/mod-plugin-builder/issues/32#issuecomment-427568447

**Comment by romi1502** [comment]
Thanks @brummer10  for the help. 
Removing the build of Camomile actually makes it work. 
I've just discovered that there is a prebuilt image on docker hub, which is much handier.
