### ISSUE TITLE
some plugins fail to build with aarch64

### ISSUE THREAD

**Issue by falkTX** [moddevices/mod-plugin-builder#43]
Currently broken for aarch64:
- blop
- camomile
- commercial-plugin-example
- zam-plugins

weird errors regarding bundles:
- artyfx
- fomp
- invada
- qmidiarp (no bundles defined)

**Comment by BramGiesen** [comment]
There are also some plugins who still have qemu(32-bit)patches, mostly for running .ttl generators. I would be in favor of just bypassing the ttl generators because I believe that in most, maybe all cases the files from the lv2-data repo are being used.

**Comment by falkTX** [comment]
bypassing the ttl generation is possible yeah, but needs patching of the build system.
I have to disable the qemu-arm things as otherwise it fails to run things for aarch64.

There are ways to natively run arm and aarch64 binaries on your 64bit system.
The docker image has instructions as it sets it up for himself, but they will work on ubuntu based distros only.

**Comment by falkTX** [comment]
sorcer and synthv1 are now fixed and working in a new branch I started, regarding multi-platform support.
blop is also failing to work for arm, not just aarch64, something to see soon...

**Comment by falkTX** [comment]
forgot about this... all plugins build now except camomile. closing.
