### ISSUE TITLE
readme deps, libtool-bin doesn't exist

### ISSUE THREAD

**Issue by ssj71** [moddevices/mod-plugin-builder#5]
at least on ubuntu 14.04. Libtool does, and changing it to that made the install work

from the current readme:
sudo apt-get install acl bc curl cvs git mercurial rsync subversion wget \
bison bzip2 flex gawk gperf gzip help2man nano perl patch tar texinfo unzip \
automake binutils build-essential cpio **libtool-bin** libncurses-dev pkg-config

**Comment by falkTX** [comment]
libtool-bin is needed for ubuntu 16.04 though, otherwise we cannot build it.
