### ISSUE TITLE
fresh debian x64, /lib/ld-linux-armhf.so.3: No such file or directory

### ISSUE THREAD

**Issue by jeremybernstein** [moddevices/mod-plugin-builder#7]
I get this when attempting to build shiro-plugins, for instance. The Docker image doesn't have this problem. It appears that some copy step, or some config step has been skipped, since the required files can be found in mod-workdir/toolchain/arm-linux-gnueabihf/sysroot/lib

**Comment by jeremybernstein** [comment]
Same on Ubuntu 16.0.4LTS

**Comment by falkTX** [comment]
I'm closing this bug since it's basically the same as #6.
Some of the provided plugin packages need to run armhf binaries.
